// Generated by CoffeeScript 1.7.1
(function() {
  var cube;

  cube = (function(_this) {
    return function(x) {
      return x * x * x;
    };
  })(this);

}).call(this);

//# sourceMappingURL=second.map
